In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("Dataset.csv", sep = ',', names=['isIPInURL','isLongURL','isTinyURL','isAlphaNumericURL','isRedirectingURL','isHypenURL','isMultiDomainURL','isFaviconDomainUnidentical','isIllegalHttpsURL','isImgFromDifferentDomain','isAnchorFromDifferentDomain','isScLnkFromDifferentDomain','isFormActionInvalid','isMailToAvailable','isStatusBarTampered','isIframePresent'])

In [3]:
label = pd.read_csv("Target_Labels.csv", sep = ',', names=['isMalicius'])

In [4]:
data.head()

isIPInURL  isLongURL  ...  isStatusBarTampered  isIframePresent
0         -1          1  ...                    1                1
1          1          1  ...                    1                1
2          1          0  ...                    1                1
3          1          0  ...                    1                1
4          1          0  ...                   -1                1

[5 rows x 16 columns]

In [5]:
data.shape

(11055, 16)

In [6]:
label.head()

isMalicius
0          -1
1          -1
2          -1
3          -1
4           1

In [7]:
label.shape

(11055, 1)

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train , x_test , y_train , y_test = train_test_split(data , label , test_size = 0.10,random_state =2)

In [11]:
x_train.shape

(9949, 16)

In [12]:
x_test.shape

(1106, 16)

In [13]:
y_train.shape

(9949, 1)

In [14]:
y_test.shape

(1106, 1)

In [15]:
reg = LinearRegression().fit(x_train,y_train)

In [16]:
reg.score(x_test,y_test)

0.5497373943250123

In [17]:
reg.coef_

array([[ 0.06518815, -0.03345382, -0.18375574,  0.04878823,  0.15600105,
         0.16861936,  0.15228627, -0.06336948, -0.05475551,  0.10851221,
         0.78469759,  0.16289871,  0.17741376,  0.01680858,  0.06235815,
        -0.02509058]])

In [18]:
reg.intercept_

array([0.37675037])

In [19]:
reg.predict(x_test)

array([[ 0.16930882],
       [-1.10014087],
       [-0.61396029],
       ...,
       [ 1.25686118],
       [-0.41420861],
       [ 1.35629121]])